name: points
description: An example social media app, written in dart with Flutter and supabase as a backend
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  # Flutter and extensions
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0

  # Icons and fonts
  google_fonts: ^6.2.1
  ionicons: ^0.2.2

  # Widgets
  scrollable_positioned_list: ^0.3.8
  grouped_list: ^6.0.0
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  badges: ^3.1.2
  flutter_svg: ^2.1.0
  package_info_plus: ^8.3.0
  simple_speed_dial: ^0.1.7
  adaptive_dialog: ^2.4.1
  infinite_scroll_pagination: ^5.0.0
  in_app_notification: ^1.1.2
  flutter_parsed_text: ^2.2.1
  dash_chat:
    git: https://github.com/bit-burger/dash_chat.git

  # State management
  flutter_form_bloc: ^0.31.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  # Configuration
  flutter_dotenv: ^5.2.1

  # Supabase
  supabase_flutter: ^2.8.4
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.3

  # Own packages
  auth_repository:
    path: ./packages/auth_repository
  user_repositories:
    path: ./packages/user_repositories
  meta_repository:
    path: ./packages/meta_repository
  chat_repository:
    path: ./packages/chat_repository
  notification_repository:
    path: ./packages/notification_repository

dependency_overrides:
  supabase:
    git: https://github.com/bit-burger/supabase-dart

dev_dependencies:
  # Tools
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

  # Test framework
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter

  # Raw packages (without Flutter)
  supabase: ^2.6.3
  hive: ^2.2.3

  # Mocking and faking
  faker: ^2.2.0
  mocktail: ^1.0.4

flutter:
  assets:
    - .env
    - google_fonts/
    - icons/logo.svg

flutter_native_splash:
  color: DDE6E8
  image: icons/logo-with-text-clear.png

flutter_icons:
  adaptive_icon_background: DDE6E8
  image_path_android: icons/logo-clear.png
  android: true
  ios: true
  image_path_ios: icons/logo-filled.png